runator_weather_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: RunatorWeatherBundle:Default:index }

runator_weather_geo:
    pattern:  /geoweather
    defaults: { _controller: RunatorWeatherBundle:Default:weather }